// studentRecords.ts

export interface Student {
  id: number;
  name: string;
  age: number;
  gender: "Male" | "Female";
  course: string;
  department: string;
  semester: number;
  email: string;
  phone: string;
  city: string;
  percentage: number;
  attendance: number;
  status: "Active" | "Inactive";
}

export const students: Student[] = [
  {
    id: 1,
    name: "Ananya Sharma",
    age: 21,
    gender: "Female",
    course: "B.Tech",
    department: "Computer Science",
    semester: 6,
    email: "ananya.sharma@gmail.com",
    phone: "9876543210",
    city: "Bangalore",
    percentage: 87.5,
    attendance: 92,
    status: "Active",
  },
  {
    id: 2,
    name: "Rahul Kumar",
    age: 22,
    gender: "Male",
    course: "B.Tech",
    department: "Information Technology",
    semester: 8,
    email: "rahul.kumar@gmail.com",
    phone: "9876543211",
    city: "Mysore",
    percentage: 78.4,
    attendance: 85,
    status: "Active",
  },
  {
    id: 3,
    name: "Priya Reddy",
    age: 20,
    gender: "Female",
    course: "BCA",
    department: "Computer Applications",
    semester: 4,
    email: "priya.reddy@gmail.com",
    phone: "9876543212",
    city: "Hyderabad",
    percentage: 91.2,
    attendance: 96,
    status: "Active",
  },
  {
    id: 4,
    name: "Arjun Singh",
    age: 23,
    gender: "Male",
    course: "B.Tech",
    department: "Electronics",
    semester: 8,
    email: "arjun.singh@gmail.com",
    phone: "9876543213",
    city: "Delhi",
    percentage: 74.8,
    attendance: 81,
    status: "Active",
  },
  {
    id: 5,
    name: "Sneha Patil",
    age: 21,
    gender: "Female",
    course: "B.Sc",
    department: "Computer Science",
    semester: 6,
    email: "sneha.patil@gmail.com",
    phone: "9876543214",
    city: "Pune",
    percentage: 89.6,
    attendance: 94,
    status: "Active",
  },
  {
    id: 6,
    name: "Vivek Raj",
    age: 22,
    gender: "Male",
    course: "BCA",
    department: "Computer Applications",
    semester: 6,
    email: "vivek.raj@gmail.com",
    phone: "9876543215",
    city: "Chennai",
    percentage: 82.3,
    attendance: 88,
    status: "Active",
  },
  {
    id: 7,
    name: "Kavya Nair",
    age: 20,
    gender: "Female",
    course: "B.Tech",
    department: "Information Science",
    semester: 4,
    email: "kavya.nair@gmail.com",
    phone: "9876543216",
    city: "Bangalore",
    percentage: 94.1,
    attendance: 97,
    status: "Active",
  },
  {
    id: 8,
    name: "Rohan Mehta",
    age: 23,
    gender: "Male",
    course: "B.Tech",
    department: "Mechanical Engineering",
    semester: 8,
    email: "rohan.mehta@gmail.com",
    phone: "9876543217",
    city: "Mumbai",
    percentage: 69.5,
    attendance: 76,
    status: "Active",
  },
  {
    id: 9,
    name: "Divya Rao",
    age: 21,
    gender: "Female",
    course: "B.Tech",
    department: "Electronics",
    semester: 6,
    email: "divya.rao@gmail.com",
    phone: "9876543218",
    city: "Davanagere",
    percentage: 86.7,
    attendance: 91,
    status: "Active",
  },
  {
    id: 10,
    name: "Karthik Gowda",
    age: 22,
    gender: "Male",
    course: "BCA",
    department: "Computer Applications",
    semester: 6,
    email: "karthik.gowda@gmail.com",
    phone: "9876543219",
    city: "Mangalore",
    percentage: 80.9,
    attendance: 84,
    status: "Active",
  },
];

export default students;